---
name: 'Gauge Action'
description: 'A simple gague'
inputs:
  performance-data-path:
    description: Performance results to store after test execution
    required: false
  test-command:
    description: Performance results to store after test execution
    required: true

runs:
  using: 'composite'
  steps:
    - id: run-test
      run: ${GITHUB_ACTION_PATH}/run-test.sh
      shell: bash
      env:
        TEST-COMMAND: ${{ inputs.test-command }}
    - id: get-temperature
      run: ${GITHUB_ACTION_PATH}/get-temperature.sh
      shell: bash
