name: Benchmark

on:
  push:

jobs:

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Gauge
        uses: ./
        with:
          performance-data-path: "path"
          test-command: "ls"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: benchmark
          path: |
            temperature.txt
