name: Benchmark

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Gauge
        uses: ./
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: benchmark
          path: |
            temperature.txt
